### ISSUE TITLE
Remove `__pycache__` file via `.gitignore`?

### ISSUE THREAD

**Issue by baseplate-admin** [levi2234/PhysEng#1]
Hi, awesome project by the way, I really love Physics engines.

back to topic, it seems that your project is committing `__pycache__` inside `.git` repository, maybe you can use something like [this](https://github.com/github/gitignore/blob/4488915eec0b3a45b5c63ead28f286819c0917de/Python.gitignore)

**Comment by levi2234** [comment]
Thanks! Great addition. I added it to gitignore

**Comment by baseplate-admin** [comment]
Awesome work
